M48
; DRILL file {KiCad 7.0.10} date Tue Jan 28 16:46:30 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-28T16:46:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X4.0516Y-2.0175
T2
X3.7969Y-1.9175
M30
